### ISSUE TITLE
For chrome app uploading to dev dashboard

### ISSUE THREAD

**Issue by AskarovBeknar** [c301/grunt-webstore-upload#8]
I am searching for tools to automate my workflow for chrome app development. And I am new in all this chromy things.
Please help me!
Let me explain my situation. I have several computers with chromium OS and some kiosk chrome app installed. And as far as I know auto update is already implemented through web store. So all I need is to upload my zip file to dev dashboard? And another question is - is your webstore-upload tool suitable for uploading chrome apps(not extensions).

**Comment by c301** [comment]
You are right, you just need to publish new version of the app in developer dashboard, in order to initiate autoupdate on client side.
I don't have Chrome app in webstore, but I'm pretty sure, that this grunt plugin suitable for chrome apps (at least, manual compiling/publishing process for extension and apps, are totally the same).
